apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [{
        "apiVersion": "org.citrusframework.yaks/v1alpha1",
        "kind": "Test",
        "metadata": {
          "name": "example"
        },
        "spec": {
          "source": {
            "name":"example.feature",
            "content": "Feature: hello world\n  Scenario: print slogan\n    Given YAKS does Cloud-Native BDD testing\n    Then YAKS rocks!\n"
          }
        }
      }]
    capabilities: Basic Install
    categories: Integration & Delivery
    certified: "false"
    containerImage: docker.io/apache/yaks:0.0.2
    createdAt: "2019-01-08T10:52:00Z"
    description: YAKS is a framework to help you test Apache Camel integrations running on Openshift & Kubernetes.
    repository: https://github.com/jboss-fuse/yaks
    support: Red Hat Fuse
  name: yaks.v0.0.2
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Test
      description: A YAKS test
      displayName: YAKS Test
      name: tests.org.citrusframework.yaks
      version: v1alpha1
      specDescriptors:
        - description: The test source
          displayName: Source
          path: source
        - description: The name of the test source
          displayName: Name
          path: source.name
        - description: The language of the test source
          displayName: Language
          path: source.language
        - description: The content of the test source
          displayName: Content
          path: source.content
      statusDescriptors:
        - description: The phase that the test is currently in
          displayName: Phase
          path: phase
        - description: The unique ID of the test
          displayName: Test ID
          path: testID
        - description: The version of YAKS which ran the test
          displayName: Version
          path: version
  description: |
    YAKS (Yet Another Kamel Subproject)
    ===================================

    YAKS is a platform to help you doing BDD testing on Openshift & Kubernetes.

    ## Running a YAKS test

    With the YAKS operator installed, you can run tests against deployed integrations by creating a `Test` resource.

    Tests are defined using [Gherkin](https://cucumber.io/docs/gherkin/) syntax. YAKS provides a set of custom steps which
    help to test for whether an integration is running, is producing some expected output and also whether an HTTP endpoint
    returns an expected response.

    The example below executes some dummy steps to check that Yaks has been installed correctly.

    ```
    apiVersion: org.citrusframework.yaks/v1alpha1
    kind: Test
    metadata:
      name: example
    spec:
      source:
        name: example.feature
        content: |-
          Feature: hello world

            Scenario: print slogan
              Given YAKS does Cloud-Native BDD testing
              Then YAKS rocks!
    ```

    Refer to the [Yaks repository](https://github.com/jboss-fuse/yaks) for more complex examples.

  displayName: Yaks Operator
  icon:
  - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjwhLS0gQ3JlYXRlZCB3aXRoIElua3NjYXBlIChodHRwOi8vd3d3Lmlua3NjYXBlLm9yZy8pIC0tPgoKPHN2ZwogICB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iCiAgIHhtbG5zOmNjPSJodHRwOi8vY3JlYXRpdmVjb21tb25zLm9yZy9ucyMiCiAgIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyIKICAgeG1sbnM6c3ZnPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICAgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIgogICB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIKICAgeG1sbnM6c29kaXBvZGk9Imh0dHA6Ly9zb2RpcG9kaS5zb3VyY2Vmb3JnZS5uZXQvRFREL3NvZGlwb2RpLTAuZHRkIgogICB4bWxuczppbmtzY2FwZT0iaHR0cDovL3d3dy5pbmtzY2FwZS5vcmcvbmFtZXNwYWNlcy9pbmtzY2FwZSIKICAgd2lkdGg9IjEyMG1tIgogICBoZWlnaHQ9IjEyMG1tIgogICB2aWV3Qm94PSIwIDAgMTIwIDEyMCIKICAgdmVyc2lvbj0iMS4xIgogICBpZD0ic3ZnOCIKICAgaW5rc2NhcGU6dmVyc2lvbj0iMC45Mi4zICgyNDA1NTQ2LCAyMDE4LTAzLTExKSIKICAgc29kaXBvZGk6ZG9jbmFtZT0ibG9nby5zdmciPgogIDxkZWZzCiAgICAgaWQ9ImRlZnMyIj4KICAgIDxsaW5lYXJHcmFkaWVudAogICAgICAgaW5rc2NhcGU6Y29sbGVjdD0iYWx3YXlzIgogICAgICAgaWQ9ImxpbmVhckdyYWRpZW50NDU0OS03Ij4KICAgICAgPHN0b3AKICAgICAgICAgc3R5bGU9InN0b3AtY29sb3I6I2ZlOGMzMztzdG9wLW9wYWNpdHk6MSIKICAgICAgICAgb2Zmc2V0PSIwIgogICAgICAgICBpZD0ic3RvcDQ1NDUiIC8+CiAgICAgIDxzdG9wCiAgICAgICAgIHN0eWxlPSJzdG9wLWNvbG9yOiNkYTY4MGY7c3RvcC1vcGFjaXR5OjEiCiAgICAgICAgIG9mZnNldD0iMSIKICAgICAgICAgaWQ9InN0b3A0NTQ3IiAvPgogICAgPC9saW5lYXJHcmFkaWVudD4KICAgIDxyYWRpYWxHcmFkaWVudAogICAgICAgaW5rc2NhcGU6Y29sbGVjdD0iYWx3YXlzIgogICAgICAgeGxpbms6aHJlZj0iI2xpbmVhckdyYWRpZW50NDU0OS03IgogICAgICAgaWQ9InJhZGlhbEdyYWRpZW50NDU1MyIKICAgICAgIGN4PSI1MCIKICAgICAgIGN5PSI1MCIKICAgICAgIGZ4PSI1MCIKICAgICAgIGZ5PSI1MCIKICAgICAgIHI9IjQ2IgogICAgICAgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiCiAgICAgICBncmFkaWVudFRyYW5zZm9ybT0ibWF0cml4KC0wLjkxNDk1NDY2LDAsMCwtMS4yMTczOTEzLDEwNS43NDc3MywxMDAuODY5NTcpIiAvPgogIDwvZGVmcz4KICA8c29kaXBvZGk6bmFtZWR2aWV3CiAgICAgaWQ9ImJhc2UiCiAgICAgcGFnZWNvbG9yPSIjZmZmZmZmIgogICAgIGJvcmRlcmNvbG9yPSIjNjY2NjY2IgogICAgIGJvcmRlcm9wYWNpdHk9IjEuMCIKICAgICBpbmtzY2FwZTpwYWdlb3BhY2l0eT0iMC4wIgogICAgIGlua3NjYXBlOnBhZ2VzaGFkb3c9IjIiCiAgICAgaW5rc2NhcGU6em9vbT0iMS40IgogICAgIGlua3NjYXBlOmN4PSIxMzMuOTc4MjEiCiAgICAgaW5rc2NhcGU6Y3k9IjIyNS40MzAyNiIKICAgICBpbmtzY2FwZTpkb2N1bWVudC11bml0cz0ibW0iCiAgICAgaW5rc2NhcGU6Y3VycmVudC1sYXllcj0ibGF5ZXIxIgogICAgIHNob3dncmlkPSJmYWxzZSIKICAgICBpbmtzY2FwZTp3aW5kb3ctd2lkdGg9IjE5MjAiCiAgICAgaW5rc2NhcGU6d2luZG93LWhlaWdodD0iMTAxNiIKICAgICBpbmtzY2FwZTp3aW5kb3cteD0iMCIKICAgICBpbmtzY2FwZTp3aW5kb3cteT0iMjciCiAgICAgaW5rc2NhcGU6d2luZG93LW1heGltaXplZD0iMSIgLz4KICA8bWV0YWRhdGEKICAgICBpZD0ibWV0YWRhdGE1Ij4KICAgIDxyZGY6UkRGPgogICAgICA8Y2M6V29yawogICAgICAgICByZGY6YWJvdXQ9IiI+CiAgICAgICAgPGRjOmZvcm1hdD5pbWFnZS9zdmcreG1sPC9kYzpmb3JtYXQ+CiAgICAgICAgPGRjOnR5cGUKICAgICAgICAgICByZGY6cmVzb3VyY2U9Imh0dHA6Ly9wdXJsLm9yZy9kYy9kY21pdHlwZS9TdGlsbEltYWdlIiAvPgogICAgICAgIDxkYzp0aXRsZT48L2RjOnRpdGxlPgogICAgICA8L2NjOldvcms+CiAgICA8L3JkZjpSREY+CiAgPC9tZXRhZGF0YT4KICA8ZwogICAgIGlua3NjYXBlOmxhYmVsPSJMYXllciAxIgogICAgIGlua3NjYXBlOmdyb3VwbW9kZT0ibGF5ZXIiCiAgICAgaWQ9ImxheWVyMSIKICAgICB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwLC0xNzcpIj4KICAgIDxnCiAgICAgICBpbmtzY2FwZTpncm91cG1vZGU9ImxheWVyIgogICAgICAgaWQ9ImxheWVyMiIKICAgICAgIGlua3NjYXBlOmxhYmVsPSJMYXllciAyIgogICAgICAgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCwxOTcpIj4KICAgICAgPHJlY3QKICAgICAgICAgc3R5bGU9Im9wYWNpdHk6MC45Nzk5OTk5ODtmaWxsOnVybCgjcmFkaWFsR3JhZGllbnQ0NTUzKTtmaWxsLW9wYWNpdHk6MTtzdHJva2U6bm9uZTtzdHJva2Utd2lkdGg6Ni4wOTA0NDc5O3N0cm9rZS1saW5lam9pbjpyb3VuZDtzdHJva2UtbWl0ZXJsaW1pdDo0O3N0cm9rZS1kYXNoYXJyYXk6bm9uZTtzdHJva2Utb3BhY2l0eToxO3BhaW50LW9yZGVyOnN0cm9rZSBmaWxsIG1hcmtlcnMiCiAgICAgICAgIGlkPSJyZWN0ODQ0IgogICAgICAgICB3aWR0aD0iMTEyIgogICAgICAgICBoZWlnaHQ9IjExMiIKICAgICAgICAgeD0iNCIKICAgICAgICAgeT0iLTE2IgogICAgICAgICByeT0iMTMuOTQzNzM3IiAvPgogICAgICA8ZwogICAgICAgICBhcmlhLWxhYmVsPSItIgogICAgICAgICB0cmFuc2Zvcm09InNjYWxlKDEuMDM1MDIxNSwwLjk2NjE2MzUxKSIKICAgICAgICAgc3R5bGU9ImZvbnQtc3R5bGU6bm9ybWFsO2ZvbnQtdmFyaWFudDpub3JtYWw7Zm9udC13ZWlnaHQ6bm9ybWFsO2ZvbnQtc3RyZXRjaDpub3JtYWw7Zm9udC1zaXplOjUwLjM1MjM5NzkycHg7bGluZS1oZWlnaHQ6MS4yNTtmb250LWZhbWlseTpNZWVyYTstaW5rc2NhcGUtZm9udC1zcGVjaWZpY2F0aW9uOk1lZXJhO2xldHRlci1zcGFjaW5nOjBweDt3b3JkLXNwYWNpbmc6MHB4O2ZpbGw6IzAzMDM0MDtmaWxsLW9wYWNpdHk6MTtzdHJva2U6bm9uZTtzdHJva2Utd2lkdGg6MC4yNjIyNTIwNiIKICAgICAgICAgaWQ9InRleHQ4MzQiPgogICAgICAgIDxwYXRoCiAgICAgICAgICAgZD0iTSA0Ni41ODQ1NzMsMzUuMTkwNzMyIEggNjkuMjQzMTUgYyAwLjY3MTM2NiwwIDEuMjg2Nzg0LC0wLjY3MTM2NSAxLjI4Njc4NCwtMS41MTA1NzIgdiAtMy40MTI3NzMgYyAwLC0wLjgzOTIwNyAtMC40NDc1NzcsLTEuMjg2NzgzIC0xLjI4Njc4NCwtMS4yODY3ODMgSCA0Ni41ODQ1NzMgYyAtMC42NzEzNjYsMCAtMS4xNzQ4OSwwLjUwMzUyNCAtMS4xNzQ4OSwxLjI4Njc4MyB2IDMuNDEyNzczIGMgMCwwLjk1MTEwMSAwLjUwMzUyNCwxLjUxMDU3MiAxLjE3NDg5LDEuNTEwNTcyIHoiCiAgICAgICAgICAgc3R5bGU9ImZvbnQtc3R5bGU6bm9ybWFsO2ZvbnQtdmFyaWFudDpub3JtYWw7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LXN0cmV0Y2g6bm9ybWFsO2ZvbnQtc2l6ZTo1NS45NDcxMDU0MXB4O2ZvbnQtZmFtaWx5OidDb3VyaWVyIDEwIFBpdGNoJzstaW5rc2NhcGUtZm9udC1zcGVjaWZpY2F0aW9uOidDb3VyaWVyIDEwIFBpdGNoIEJvbGQnO2ZpbGw6IzAzMDM0MDtmaWxsLW9wYWNpdHk6MTtzdHJva2Utd2lkdGg6MC4yNjIyNTIwNiIKICAgICAgICAgICBpZD0icGF0aDg3MCIgLz4KICAgICAgPC9nPgogICAgPC9nPgogICAgPGcKICAgICAgIGFyaWEtbGFiZWw9Il0iCiAgICAgICB0cmFuc2Zvcm09Im1hdHJpeCgwLDAuOTM4MjQ3NzgsLTEuMDY1ODE2NSwwLDAsMCkiCiAgICAgICBzdHlsZT0iZm9udC1zdHlsZTpub3JtYWw7Zm9udC12YXJpYW50Om5vcm1hbDtmb250LXdlaWdodDpib2xkO2ZvbnQtc3RyZXRjaDpub3JtYWw7Zm9udC1zaXplOjg2LjQxNzU1Njc2cHg7bGluZS1oZWlnaHQ6MS4yNTtmb250LWZhbWlseTonQ291cmllciAxMCBQaXRjaCc7LWlua3NjYXBlLWZvbnQtc3BlY2lmaWNhdGlvbjonQ291cmllciAxMCBQaXRjaCBCb2xkJztsZXR0ZXItc3BhY2luZzowcHg7d29yZC1zcGFjaW5nOjBweDtmaWxsOiNmNWZmZmY7ZmlsbC1vcGFjaXR5OjE7c3Ryb2tlOm5vbmU7c3Ryb2tlLXdpZHRoOjAuNDUwMDkxMzkiCiAgICAgICBpZD0idGV4dDgxNyI+CiAgICAgIDxwYXRoCiAgICAgICAgIGQ9Im0gMjIwLjQ1MTE4LC04OS4xMzM1NCBoIC0xMi45NjI2MyBjIC0xLjgxNDc3LDAgLTIuODUxNzgsMS4yMDk4NDYgLTIuODUxNzgsMy4yODM4NjcgMCwyLjA3NDAyMiAxLjEyMzQzLDMuMjgzODY3IDIuOTM4MTksMy4yODM4NjcgaCA2LjMwODQ5IHYgNTIuNDU1NDU3IGggLTYuMzA4NDkgYyAtMS44MTQ3NiwwIC0yLjkzODE5LDEuMjk2MjY0IC0yLjkzODE5LDMuMzcwMjg1IDAsMi4wNzQwMjEgMS4wMzcwMSwzLjI4Mzg2NyAyLjg1MTc4LDMuMjgzODY3IGggMTIuOTYyNjMgYyAyLjA3NDAyLDAgMy4zNzAyOSwtMS4yMDk4NDYgMy4zNzAyOSwtMi43NjUzNjIgdiAtNjAuMTQ2NjE5IGMgMCwtMS41NTU1MTYgLTEuMjk2MjcsLTIuNzY1MzYyIC0zLjM3MDI5LC0yLjc2NTM2MiB6IgogICAgICAgICBzdHlsZT0iZm9udC1zdHlsZTpub3JtYWw7Zm9udC12YXJpYW50Om5vcm1hbDtmb250LXdlaWdodDpib2xkO2ZvbnQtc3RyZXRjaDpub3JtYWw7Zm9udC1mYW1pbHk6J0NvdXJpZXIgMTAgUGl0Y2gnOy1pbmtzY2FwZS1mb250LXNwZWNpZmljYXRpb246J0NvdXJpZXIgMTAgUGl0Y2ggQm9sZCc7ZmlsbDojZjVmZmZmO2ZpbGwtb3BhY2l0eToxO3N0cm9rZS13aWR0aDowLjQ1MDA5MTM5IgogICAgICAgICBpZD0icGF0aDg2NCIgLz4KICAgIDwvZz4KICAgIDxnCiAgICAgICBhcmlhLWxhYmVsPSI6IgogICAgICAgdHJhbnNmb3JtPSJtYXRyaXgoMCwwLjkyNDY4NDgsLTEuMDgxNDQ5NiwwLDAsMCkiCiAgICAgICBzdHlsZT0iZm9udC1zdHlsZTpub3JtYWw7Zm9udC12YXJpYW50Om5vcm1hbDtmb250LXdlaWdodDpub3JtYWw7Zm9udC1zdHJldGNoOm5vcm1hbDtmb250LXNpemU6MTE2LjYyNjkxNDk4cHg7bGluZS1oZWlnaHQ6MS4yNTtmb250LWZhbWlseTpNZWVyYTstaW5rc2NhcGUtZm9udC1zcGVjaWZpY2F0aW9uOk1lZXJhO2xldHRlci1zcGFjaW5nOjBweDt3b3JkLXNwYWNpbmc6MHB4O2ZpbGw6IzAzMDM0MDtmaWxsLW9wYWNpdHk6MTtzdHJva2U6bm9uZTtzdHJva2Utd2lkdGg6MC42MDc0MzE5NSIKICAgICAgIGlkPSJ0ZXh0ODE3LTMiPgogICAgICA8cGF0aAogICAgICAgICBkPSJtIDIzNC42NzQ1NiwtNDAuNDM2MjE2IGMgMCw2LjE4MTIyNiA0LjY2NTA4LDEwLjg0NjMwMyAxMS43NzkzMiwxMC44NDYzMDMgNy4xMTQyNCwwIDEyLjAxMjU3LC00LjU0ODQ1IDEyLjAxMjU3LC0xMC44NDYzMDMgMCwtNi4xODEyMjcgLTQuNzgxNywtMTAuNjEzMDQ5IC0xMi4wMTI1NywtMTAuNjEzMDQ5IC03LjExNDI0LDAgLTExLjc3OTMyLDQuNDMxODIyIC0xMS43NzkzMiwxMC42MTMwNDkgeiBtIDAsLTMwLjMyMjk5OCBjIDAsNi4xODEyMjYgNC43ODE3LDEwLjg0NjMwMyAxMS44OTU5NSwxMC44NDYzMDMgNy4xMTQyNCwwIDExLjc3OTMxLC00LjU0ODQ1IDExLjc3OTMxLC0xMC44NDYzMDMgMCwtNi4xODEyMjcgLTQuNTQ4NDQsLTEwLjYxMzA0OSAtMTEuNzc5MzEsLTEwLjYxMzA0OSAtNy4yMzA4NywwIC0xMS44OTU5NSw0LjQzMTgyMiAtMTEuODk1OTUsMTAuNjEzMDQ5IHoiCiAgICAgICAgIHN0eWxlPSJmb250LXN0eWxlOm5vcm1hbDtmb250LXZhcmlhbnQ6bm9ybWFsO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zdHJldGNoOm5vcm1hbDtmb250LWZhbWlseTonQ291cmllciAxMCBQaXRjaCc7LWlua3NjYXBlLWZvbnQtc3BlY2lmaWNhdGlvbjonQ291cmllciAxMCBQaXRjaCBCb2xkJztmaWxsOiMwMzAzNDA7ZmlsbC1vcGFjaXR5OjE7c3Ryb2tlLXdpZHRoOjAuNjA3NDMxOTUiCiAgICAgICAgIGlkPSJwYXRoODY3IiAvPgogICAgPC9nPgogICAgPGcKICAgICAgIGFyaWEtbGFiZWw9IiZndDsiCiAgICAgICB0cmFuc2Zvcm09Im1hdHJpeCgwLDAuODkxMzAzOTcsLTEuMTIxOTUxNywwLDAsMCkiCiAgICAgICBzdHlsZT0iZm9udC1zdHlsZTpub3JtYWw7Zm9udC12YXJpYW50Om5vcm1hbDtmb250LXdlaWdodDpub3JtYWw7Zm9udC1zdHJldGNoOm5vcm1hbDtmb250LXNpemU6NjUuNDgzNTU4NjVweDtsaW5lLWhlaWdodDoxLjI1O2ZvbnQtZmFtaWx5Ok1lZXJhOy1pbmtzY2FwZS1mb250LXNwZWNpZmljYXRpb246TWVlcmE7bGV0dGVyLXNwYWNpbmc6MHB4O3dvcmQtc3BhY2luZzowcHg7ZmlsbDojZmZmZmZmO2ZpbGwtb3BhY2l0eToxO3N0cm9rZTpub25lO3N0cm9rZS13aWR0aDowLjM0MTA2MDE2IgogICAgICAgaWQ9InRleHQ4MTctMzIiPgogICAgICA8cGF0aAogICAgICAgICBkPSJtIDI4NS4wMjM3NiwtNjIuOTczMzU1IDIwLjI5OTksOS40OTUxMTYgLTIwLjI5OTksOS40Mjk2MzMgYyAtMS41NzE2MSwwLjcyMDMxOSAtMi4yOTE5MywxLjU3MTYwNSAtMi4yOTE5MywzLjA3NzcyNyAwLDEuOTY0NTA3IDEuMTc4NzEsMy41MzYxMTIgMi45NDY3NiwzLjUzNjExMiAwLjY1NDg0LDAgMS4zMDk2NywtMC4yNjE5MzQgMi4yMjY0NCwtMC42NTQ4MzYgbCAyNS41Mzg1OSwtMTEuOTE4MDA3IGMgMS45NjQ1MSwtMC45MTY3NyAyLjk0Njc2LC0xLjgzMzU0IDIuOTQ2NzYsLTMuNDcwNjI5IDAsLTEuNjM3MDg5IC0wLjk4MjI1LC0yLjU1Mzg1OSAtMi45NDY3NiwtMy40NzA2MjggbCAtMjUuNTM4NTksLTExLjkxODAwOCBjIC0wLjkxNjc3LC0wLjM5MjkwMiAtMS41NzE2LC0wLjY1NDgzNiAtMi4yMjY0NCwtMC42NTQ4MzYgLTEuNzY4MDUsMCAtMi45NDY3NiwxLjUwNjEyMiAtMi45NDY3NiwzLjQ3MDYyOSAwLDEuNTA2MTIyIDAuNzIwMzIsMi4zNTc0MDggMi4yOTE5MywzLjA3NzcyNyB6IgogICAgICAgICBzdHlsZT0iZm9udC1zdHlsZTpub3JtYWw7Zm9udC12YXJpYW50Om5vcm1hbDtmb250LXdlaWdodDpib2xkO2ZvbnQtc3RyZXRjaDpub3JtYWw7Zm9udC1mYW1pbHk6J0NvdXJpZXIgMTAgUGl0Y2gnOy1pbmtzY2FwZS1mb250LXNwZWNpZmljYXRpb246J0NvdXJpZXIgMTAgUGl0Y2ggQm9sZCc7ZmlsbDojZmZmZmZmO2ZpbGwtb3BhY2l0eToxO3N0cm9rZS13aWR0aDowLjM0MTA2MDE2IgogICAgICAgICBpZD0icGF0aDg3MyIgLz4KICAgIDwvZz4KICA8L2c+Cjwvc3ZnPgo=
    mediatype: image/svg+xml
  install:
    spec:
      deployments:
      - name: yaks
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: yaks
          strategy: {}
          template:
            metadata:
              labels:
                name: yaks
            spec:
              containers:
              - command:
                - yaks
                - operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: yaks
                image: docker.io/yaks/yaks:0.0.2
                imagePullPolicy: IfNotPresent
                name: yaks
                resources: {}
              serviceAccountName: yaks
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - configmaps
          - secrets
          - serviceaccounts
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods/log
          - pods/status
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - roles
          - rolebindings
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - org.citrusframework.yaks
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: yaks
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
    - yaks
    - testing
    - microservices
  labels:
    name: yaks-operator
  links:
    - name: YAKS source code repository
      url: https://github.com/jboss-fuse/yaks
# TODO: To be confirmed...
#  maintainers:
#    - email:
#      name:
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.2
