apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tests.org.citrusframework.yaks
spec:
  group: org.citrusframework.yaks
  names:
    kind: Test
    listKind: TestList
    plural: tests
    singular: test
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Phase
    type: string
    description: The test phase
    JSONPath: .status.phase
  - name: Total
    type: string
    description: The total amount of tests
    JSONPath: .status.results.summary.total
  - name: Passed
    type: string
    description: Passed tests
    JSONPath: .status.results.summary.passed
  - name: Failed
    type: string
    description: Failed tests
    JSONPath: .status.results.summary.failed
  - name: Skipped
    type: string
    description: Skipped tests
    JSONPath: .status.results.summary.skipped
  - name: Errors
    type: string
    description: Test error details
    priority: 1
    JSONPath: .status.errors
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            source:
              properties:
                content:
                  type: string
                language:
                  type: string
                name:
                  type: string
              type: object
          type: object
        status:
          properties:
            phase:
              type: string
            results:
              properties:
                summary:
                  properties:
                    total:
                      type: number
                    passed:
                      type: number
                    failed:
                      type: number
                    skipped:
                      type: number
                    pending:
                      type: number
                    undefined:
                      type: number
                  type: object
                tests:
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      errorType:
                        type: string
                      errorMessage:
                        type: string
                  type: array
              type: object
            testID:
              type: string
            version:
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
