kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: yaks
subjects:
- kind: ServiceAccount
  name: yaks
roleRef:
  kind: Role
  name: yaks
  apiGroup: rbac.authorization.k8s.io
